FROM python:3.10-slim

WORKDIR /app

RUN apt-get update
RUN apt-get install locales locales-all -y
RUN apt update && apt install tzdata -y

ENV TZ="America/Sao_Paulo"
ENV LC_ALL pt_BR.UTF-8
ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR.UTF-8

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 8080
CMD ["gunicorn", "flask_backend:create_app()", "--workers", "4", "--bind", "0.0.0.0:8080"]