version: '3.8'

services:
  traefik:
    image: traefik:v2.2
    container_name: cinemaempoa_traefik
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesResolvers.lets-encrypt.acme.email=${ACME_EMAIL:?Please set the ACME_EMAIL env variable}"
      - "--certificatesResolvers.lets-encrypt.acme.tlsChallenge=true"
      - "--certificatesResolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - web

  flask:
    container_name: cinemaempoa_flask
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
    networks:
      - web
    expose:
      - 8080

  nginx:
    image: nginx:stable-alpine
    container_name: cinemaempoa_nginx
    volumes:
      - .:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    labels:
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.rule=Host(`cinemaempoa.com.br`)"
      - "traefik.http.routers.nginx.tls.certresolver=lets-encrypt"
    networks:
      - web
volumes:
  letsencrypt:
networks:
  web:
    external: false

