"""Add directors table

Revision ID: abf989edaadb
Revises: 20251124_201556
Create Date: 2025-12-19 16:26:34.524218

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abf989edaadb"
down_revision: Union[str, None] = "20251124_201556"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_directors_name"), "directors", ["name"], unique=False)
    op.create_index(op.f("ix_directors_slug"), "directors", ["slug"], unique=False)
    op.create_table(
        "movie_directors",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("director_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["director_id"],
            ["directors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "director_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_directors")
    op.drop_index(op.f("ix_directors_slug"), table_name="directors")
    op.drop_index(op.f("ix_directors_name"), table_name="directors")
    op.drop_table("directors")
    # ### end Alembic commands ###
