"""Data access for AlertAction rows - the append-only posted/dismissed
action log behind /admin/alerts (issue #258). Replaces repository/alerts.py:
unlike the old Alert rows, these aren't generated by a pipeline - they're
only ever created by an admin action, and "which screenings are currently
pending" is answered live (see flask_backend/service/screening_alerts.py),
not by querying this table directly.
"""

from datetime import date, datetime
from math import ceil
from typing import Dict, List, Optional, Tuple

from sqlalchemy import func

from flask_backend.db import db_session
from flask_backend.models import AlertAction


def create(
    screening_id: int,
    action: str,
    remind_at: Optional[date] = None,
    created_by_user_id: Optional[int] = None,
    commit: bool = True,
) -> AlertAction:
    alert_action = AlertAction(
        screening_id=screening_id,
        action=action,
        remind_at=remind_at,
        created_at=datetime.now(),
        created_by_user_id=created_by_user_id,
    )
    db_session.add(alert_action)
    if commit:
        db_session.commit()
        db_session.refresh(alert_action)
    return alert_action


def get_latest_by_screening_ids(screening_ids: List[int]) -> Dict[int, AlertAction]:
    """Most recent AlertAction per screening_id (ties broken by id), for
    whichever of `screening_ids` have at least one action."""
    if not screening_ids:
        return {}
    rows = (
        db_session.query(AlertAction)
        .filter(AlertAction.screening_id.in_(screening_ids))
        .order_by(
            AlertAction.screening_id,
            AlertAction.created_at.desc(),
            AlertAction.id.desc(),
        )
        .all()
    )
    latest: Dict[int, AlertAction] = {}
    for row in rows:
        if row.screening_id not in latest:
            latest[row.screening_id] = row
    return latest


def get_paginated(
    action: Optional[str], current_page: int, per_page: int
) -> Tuple[List[AlertAction], int, int]:
    offset_value = (current_page - 1) * per_page

    query = db_session.query(AlertAction)
    if action is not None:
        query = query.filter(AlertAction.action == action)

    query = (
        query.order_by(AlertAction.created_at.desc())
        .limit(per_page)
        .offset(offset_value)
    )
    actions = query.all()

    count_query = db_session.query(func.count(AlertAction.id))
    if action is not None:
        count_query = count_query.filter(AlertAction.action == action)
    total_count = count_query.scalar()
    total_pages = ceil(total_count / per_page) if total_count else 0

    return (actions, total_pages, total_count)


def delete_for_screening(screening_id: int) -> None:
    db_session.query(AlertAction).filter(
        AlertAction.screening_id == screening_id
    ).delete(synchronize_session=False)


def repoint_to_screening(old_screening_id: int, new_screening_id: int) -> None:
    db_session.query(AlertAction).filter(
        AlertAction.screening_id == old_screening_id
    ).update({"screening_id": new_screening_id})
