name: CI (PR)

on:
  pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.3
            - uses: actions/setup-python@v5.1.0
              with:
                python-version: '3.10'
            - run: pip install -r requirements.txt
            - run: ruff check