name: Import CineBancarios

on:
  schedule:
    - cron: "0 0 * * 5" # At 00:00 UTC friday = 21:00 BRT thursday (every 7 days)
    - cron: "0 9 * * 5" # At 09:00 UTC friday = 06:00 BRT friday (every 7 days)
  workflow_dispatch:

jobs:
  import-cinebancarios:
    if: ${{ github.repository == 'cumbucadev/cinemaempoa' }}
    name: Import CineBancarios
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker exec cinemaempoa_flask bash -c "python cinemaempoa.py -r cinebancarios > /app/import.json"
            docker exec cinemaempoa_flask bash -c "flask --app flask_backend import-json /app/import.json"
