name: Run Spiders

on:
  schedule:
    - cron: "0 3,15 * * *" # At 03:00 and 15:00 UTC every day (every 12 hours)
  workflow_dispatch:

jobs:
  run-spiders:
    if: ${{ github.repository == 'cumbucadev/cinemaempoa' }}
    name: Run Spiders
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up locale
        run: |
          sudo apt-get install -y locales
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8
        env:
          LANG: pt_BR.UTF-8
          LC_ALL: pt_BR.UTF-8

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install runner dependencies
        run: pip install -r requirements.runner.txt

      - name: Run scrapers and import
        env:
          LANG: pt_BR.UTF-8
          LC_ALL: pt_BR.UTF-8
        run: |
          python runner/main.py \
            --rooms capitolio sala-redencao paulo-amorim \
            --api-url ${{ secrets.APP_URL }} \
            --api-token ${{ secrets.IMPORT_API_TOKEN }}
